// Generated by CoffeeScript 1.5.0
(function() {
  var AhoNavigation;

  window.AhoNavigation = AhoNavigation = (function() {

    function AhoNavigation(authenticated, active, width) {
      this.authenticated = authenticated;
      this.active = active;
      this.width = width != null ? width : "1000px";
      this.sections = [
        {
          name: "Website",
          prefix: true,
          url: "http://abundantharvestorganics.com",
          color: "#83b419"
        }, {
          name: "Kitchen",
          prefix: true,
          url: "http://kitchen.abundantharvestorganics.com",
          color: "#f3b91f"
        }, {
          name: "My Account",
          prefix: false,
          url: "http://my.abundantharvestorganics.com",
          color: "#754c24"
        }
      ];
      this.nav_color = "";
      this.navigation = "";
      this.sites();
      this.sponsors();
      this.info();
      this.account();
    }

    AhoNavigation.prototype.sites = function() {
      var section, _i, _len, _ref;
      this.append("<ul id='sites-nav'>");
      _ref = this.sections;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        section = _ref[_i];
        this.append("<li class='top-nav" + section.name + "'>");
        this.append("<a href='" + section.url + "' style='background-color:" + section.color + "'>");
        if (section.prefix) {
          this.append("<span class='ah'>Abundant <br />Harvest</span>");
        }
        this.append("" + section.name + "</a></li>");
        if (section.name.toLowerCase() === this.active.toLowerCase()) {
          this.nav_color = section.color;
        }
      }
      return this.append("</ul>");
    };

    AhoNavigation.prototype.sponsors = function() {
      this.append("<ul id='sponsors-nav'>");
      this.append("<a href='http://www.usda.gov/wps/portal/usda/usdahome?navid=ORGANIC_CERTIFICATIO'><img src='logo-usda.png' /></a>");
      this.append("<a href='http://www.ccof.org/'><img src='logo-ccof.png' /></a>");
      return this.append("</ul>");
    };

    AhoNavigation.prototype.info = function() {
      this.append("<ul id='info-nav'>");
      this.append("<li><a href='http://www.abundantharvestorganics.com'>Help</a></li>|");
      this.append("<li><a href='http://www.abundantharvestorganics.com/contacts/'>Contact Us</a></li>");
      return this.append("</ul>");
    };

    AhoNavigation.prototype.account = function() {
      this.append("<ul id='account-nav'>");
      if (!this.authenticated) {
        this.append("<li><a href='http://my.abundantharvestorganics.com/signup-delivery-step1.html'>Sign Up NOW</a></li>");
      }
      this.append("<li><a href='http://www.abundantharvestorganics.com' class='tell-a-friend'>Tell A Friend</a></li>");
      return this.append("</ul>");
    };

    AhoNavigation.prototype.append = function(content) {
      return this.navigation += content;
    };

    AhoNavigation.prototype.render = function() {
      document.write("<div id='top-nav' style='border-color:" + this.nav_color + "'>");
      document.write("<div id='nav-inside' style='width:" + this.width + "'>");
      document.write(this.navigation);
      document.write("</div>");
      return document.write("</div>");
    };

    return AhoNavigation;

  })();

}).call(this);
