// Generated by CoffeeScript 1.5.0
(function() {
  var AhoNavigation;

  window.AhoNavigation = AhoNavigation = (function() {

    function AhoNavigation(authenticated) {
      this.authenticated = authenticated;
      this.sections = [
        {
          name: "Website",
          prefix: true,
          url: "http://abundantharvestorganics.com"
        }, {
          name: "Kitchen",
          prefix: true,
          url: "http://kitchen.abundantharvestorganics.com"
        }, {
          name: "My Account",
          prefix: false,
          url: "http://my.abundantharvestorganics.com"
        }
      ];
      this.navigation = "";
      this.sites();
      this.sponsors();
      this.info();
      this.account();
    }

    AhoNavigation.prototype.sites = function() {
      var section, _i, _len, _ref;
      this.append("<ul id='sites-nav'>");
      _ref = this.sections;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        section = _ref[_i];
        this.append("<li class='top-nav" + section.name + "'>");
        this.append("<a href='" + section.url + "'>");
        if (section.prefix) {
          this.append("<span class='ah'>Abundant <br />Harvest</span>");
        }
        this.append("" + section.name + "</a></li>");
      }
      return this.append("</ul>");
    };

    AhoNavigation.prototype.sponsors = function() {
      this.append("<ul id='sponsors-nav'>");
      this.append("<a href='http://www.usda.gov/wps/portal/usda/usdahome?navid=ORGANIC_CERTIFICATIO'><img src='logo-usda.png' /></a>");
      this.append("<a href='http://www.ccof.org/'><img src='logo-ccof.png' /></a>");
      return this.append("</ul>");
    };

    AhoNavigation.prototype.info = function() {
      this.append("<ul id='info-nav'>");
      this.append("<li><a href=''>Help</a></li>|");
      this.append("<li><a href=''>Contact Us</a></li>");
      return this.append("</ul>");
    };

    AhoNavigation.prototype.account = function() {
      this.append("<ul id='account-nav'>");
      if (!this.authenticated) {
        this.append("<li><a href=''>Sign Up NOW</a></li>");
      }
      this.append("<li><a href='' class='tell-a-friend'>Tell A Friend</a></li>");
      return this.append("</ul>");
    };

    AhoNavigation.prototype.append = function(content) {
      return this.navigation += content;
    };

    AhoNavigation.prototype.render = function() {
      document.write("<div id='top-nav'><div id='nav-inside'>");
      document.write(this.navigation);
      return document.write("</div></div>");
    };

    return AhoNavigation;

  })();

}).call(this);
